use ecommerce_Db;


ALTER TABLE ORDERS
ADD CONSTRAINT
chk_user
foreign key (UserID) references Users(UserID)
ON DELETE
CASCADE;

-- CREATING TRANSCTIONS TO INURE DATA INTEGRITY
-- SUCH THAT IF AN INVALID DATA IS ADDED TO THE TABLES IT WILL AUTOMATICALLY ROLLBACK TO THE ORIGINAL TABLE

START TRANSACTION;

INSERT INTO ORDERS(ORDERID,USERID,OrderDate,TotalAmount)
VALUES(1009,70,CURDATE(),"ANKIT");

COMMIT;

-- IF SOMETHING GOES WRONG
-- ROLLBACK WILL UNDO ALL THE TRANSACTION MADE, ENSURING DB REMAINS CONSTANT
rollback;

-- DATA IS NOT ADDED TO THE TABLE AND ROLLED BACK TO ORIGINAL AS TOTALAMOUNT IS OF TYPE SPRING AND NOT INT
SELECT * FROM ORDERS;